# Percy config
version: 2
snapshot:
  widths:
    - 360
    - 1366
  minHeight: 1024
storybook:
  include: ['/IBM Products/']
  exclude: [
      # Exclude the following snapshots until randomized data is removed
      '/Datagrid/ClickableRow/',
      '/Datagrid/ColumnCustomization/',
      '/Datagrid/EditableCell/',
      '/Datagrid/ExpandableRow/',
      '/Datagrid/NestedRows/',
      '/Datagrid/RowHeightSettings/',
      '/Datagrid/Slug/',
      '/Datagrid: With Virtualized Data/',
      '/DataSpreadsheet/',
      '/MultiAddSelect: With Avatars/',
      '/Tag set/TagSet: Hundreds Of Tags/',
      # Exclude the following snapshots until transitions are completed
      '/Datagrid/Filtering/Flyout: Filter flyout with initial filters/',
      '/Datagrid/Filtering/Panel: Filter panel with initial filters/',
      '/Page header/PageHeader: Page header with all items, pre-collapsed/',
    ]
