# Netlify build and deploy settings - https://docs.netlify.com/configure-builds/file-based-configuration/#sample-file
[build]
command = "yarn storybook:build"
publish = "packages/core/storybook-static"
