# Netlify build and deploy settings - https://docs.netlify.com/configure-builds/file-based-configuration/#sample-file
[build]
command = "yarn storybook:build"
publish = "packages/core/storybook-static"

[[redirects]]
  from = "https://ibm-cloud-cognitive.netlify.app/*"
  to = "https://carbon-for-ibm-products.netlify.app/:splat"
  status = 301
  force = true
