# Netlify build and deploy settings - https://docs.netlify.com/configure-builds/file-based-configuration/#sample-file
[build]
ignore = "sh ./scripts/ignore_dependabot.sh"
command = "yarn build:storybook"
publish = "packages/ibm-products-web-components/storybook-static"

[build.environment]
YARN_ENABLE_GLOBAL_CACHE = "true"
YARN_GLOBAL_FOLDER = "/opt/buildhome/.yarn_cache"
