name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: lts/fermium

      - name: Install
        run: yarn --offline

      - name: Build
        run: yarn build:packages

      - name: Package CI checks
        run: yarn run-all --no-sort ci-check

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: lts/fermium

      - name: Install
        run: yarn --offline

      - name: Audit
        run: yarn run audit

      - name: Lint
        run: yarn run lint

  storybook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: lts/fermium

      - name: Install
        run: yarn --offline

      - name: Build storybook
        run: yarn storybook:build

  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: lts/fermium

      - name: Install
        run: yarn --offline

      - name: Tests
        run: yarn test --ci
