name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: lts/fermium
          cache: yarn

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: build-dependencies-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install
        run: yarn --offline

      - name: Build
        run: yarn build

      - name: Package CI checks
        run: yarn run-all --no-sort ci-check

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: lts/fermium
          cache: yarn

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: lint-dependencies-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install
        run: yarn --offline

      - name: Audit
        run: yarn run audit

      - name: Lint
        run: yarn run lint

  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: lts/fermium
          cache: yarn

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: tests-dependencies-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install
        run: yarn --offline

      - name: Tests
        run: yarn test --ci
