name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  cancel:
    name: 'Cancel all but the latest incomplete run'
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
        with:
          all_but_latest: true
          access_token: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: lts/fermium

      - name: Install
        run: yarn --offline

      - name: Build
        run: yarn build

      - name: Package CI checks
        run: yarn run-all --no-sort ci-check

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: lts/fermium

      - name: Install
        run: yarn --offline

      - name: Audit
        run: yarn run audit

      - name: Lint
        run: yarn run lint

  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: lts/fermium

      - name: Install
        run: yarn --offline

      - name: Tests
        run: yarn test --ci
