name: v2 pre-release # Builds and releases @carbon/v11 supported version of @carbon/ibm-products

on:
  workflow_dispatch:

jobs:
  Release:
    uses: ./.github/workflows/release.yml
    with:
      release-type: '--canary preminor'
    secrets: inherit
