name: Stale # close stale issues
on:
  schedule:
    - cron: '0 8 * * *' # Runs at 8:00 every day

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@28ca1036281a5e5922ead5184a1bbf96e5fc984e #v9.0.0
        with:
          any-of-labels:
            'status: needs reproduction,status: waiting for author 💬'
          stale-issue-message: |
            This issue is stale because it has been open for 7 days with no activity.
            Remove the stale label or add a comment, otherwise this issue will be closed in 7 days.
          close-issue-message: |
            This issue was closed because it has received no activity for 14 days.
          stale-issue-label: 'stale 🍞'
          close-issue-label: 'status: won’t fix 🔚'
          days-before-stale: 7
          days-before-close: 7
          days-before-pr-close: -1
