name: storybook
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
      - name: Install Node.js
        run: nvm install
      - name: Install dependencies
        run: yarn install --offline
      - name: Build Storybook
        run: |
          cd packages/core
          yarn build
          ls -a
      - name: Deploy Storybook
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: packages/core/storybook-static
