name: Update example gallery # Updates dependencies twice a month

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 8,22 * *' # Updates will happen every 8th/22nd of the month

jobs:
  check_gallery:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: yarn

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: check-gallery-${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: Install
        run: yarn

      - name: Check gallery
        id: up_to_date
        run: |
          yarn update-gallery-config
          if [[ `git status --porcelain` ]]; then
            echo "::error ::The gallery is out of date, run yarn update-gallery-config"
            echo "The following items are out of date."
            git status --porcelain
            exit 1
          else
            echo "Gallery is up-to-date"
            exit 0
          fi

      - name: Create pull request
        if: steps.up_to_date.outcome == 'failure'
        id: create-pr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.CREATE_PR_ACCESS_TOKEN }}
          commit-message: 'chore: update example gallery'
          committer: GitHub <noreply@github.com>
          author:
            ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: 'update-examples'
          branch-suffix: random
          title: 'chore: update example gallery'
          body: |
            This PR was automatically generated to update provided examples.
            The goal is to keep our examples up-to-date with the latest changes from our own package.

            #### What did you change?

            This action ran `yarn update-gallery-config` to update examples as necessary.

            #### How did you test and verify your work?

            This PR should only be merged reviewing the following checks:
            - [ ] `yarn ci-check` runs cleanly and all tests pass.
            - [ ] Storybook runs correctly in the Netlify deploy-preview
              - [ ] Updated components render correctly in the examples section of Storybook.







  carbon:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install
        run: yarn

      - name: Update Carbon packages
        run: |
          yarn upgrade:carbon
          yarn
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false

      - name: Create PR
        id: create-pr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.CREATE_PR_ACCESS_TOKEN }}
          commit-message: 'fix: update Carbon 11 compatible versions to latest'
          committer: GitHub <noreply@github.com>
          author:
            ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: 'update-packages'
          branch-suffix: random
          title: 'fix: update to Carbon 11 compatible versions to latest'
          body: |
            This PR was automatically generated to update Carbon 11 compatible versions on a regular basis. This is not intended to create any breaking changes, and will be reflected as a minor version bump for affected packages. NB we'll run all tests and do visual verifications, but there is always the opportunity for unexpected regressions. If you're using one of the packages in a stable or production context you may want to check this before taking the next minor version, and do let us know ASAP if you see anything problematic.

            The goal is to update to the latest Carbon 11 compatible versions each Friday, to ensure we remain up-to-date with the latest changes (often published on Thursdays) and to ensure interoperability with other packages that also depend on Carbon. We will normally update all other dependencies at the same time to their latest versions, except for specific cases where we have found the updates to be problematic or require further work before they can be used. By using the latest stable version of each dependency we ensure we get fixes and improvements in a timely fashion and reduce the impact of updating the versions that can arise if versions are allowed to become stale for an extended period.

            #### What did you change?

            This action ran `yarn upgrade:carbon` to upgrade all carbon-related packages to the latest versions.

            This PR includes the various `package.json` that pull our dependencies forward to the latest versions, and updates the offline mirror.

            #### How did you test and verify your work?

            This PR should not be merged until the following checks have been made:
            - [ ] A reminder message has been posted onto the ibmproducts-pal-dev Slack channel that a version update PR is going through.
            - [ ] `yarn ci-check` runs cleanly and all tests pass (done automatically as part of the PR checks).
            - [ ] the Netlify deploy-preview has been used to ensure that storybook runs and the main published components render correctly.


  dependencies:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install
        run: yarn

      - name: Update packages
        run: |
          yarn upgrade:automatic
          rm yarn.lock
          yarn
          yarn update-gallery-config
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false

      - name: Create PR
        id: create-pr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.CREATE_PR_ACCESS_TOKEN }}
          commit-message: 'chore: update dev dependencies'
          committer: GitHub <noreply@github.com>
          author:
            ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: 'update-packages'
          branch-suffix: random
          title: 'chore: update dev dependencies'
          body: |
            This PR was automatically generated to update versions of dev dependencies to their latest versions. This helps ensure we get fixes and improvements in a timely fashion and reduces the impact of updating the versions that can arise if versions are allowed to become stale for an extended period.

            #### What did you change?

            This action ran `yarn upgrade:automatic` to update `package.json` files to request the latest versions of each package. Certain critical packages are intentionally excluded.

            This action also deleted the `yarn.lock` file in order to recreate it with the latest matching versions of secondary dependencies.

            This PR includes the various `package.json` that pull our dependencies forward to the latest versions, the `yarn.lock` update that maps required versions to the actual versions to be used, and updates the offline mirror.

            #### How did you test and verify your work?

            This PR should not normally significantly affect the build outputs or runtime packages. Ensure that `yarn ci-check` runs cleanly and all tests pass (done automatically as part of the PR checks).
